<?php

use Drupal\os2web_newsletter\Form\SettingsForm;

/**
 * Implements hook_token_info().
 *
 * Adds OS2Web Newsletter token for node render.
 */
function os2web_newsletter_token_info() {
  // Core tokens for nodes.
  $node['render_os2web_newsletter'] = array(
    'name' => t("OS2Web Newsletter display"),
    'description' => t("Node rendered using os2web_newsletter display."),
  );
  return array(
    'tokens' => array(
      'node' => $node,
    ),
  );
}

/**
 * Implements hook_tokens_alter().
 *
 * Adds relevant info via newsletter tokens.
 */
function os2web_newsletter_tokens_alter(array &$replacements, array $context, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
  if ($context['type'] == 'node' && !empty($context['data']['node'])) {
    $node = $context['data']['node'];

    // Alter the [node:title] token, and replace it with the rendered content
    // of a field (field_title).
    if (isset($context['tokens']['render_os2web_newsletter'])) {
      // Setting front-end theme.
      /** @var \Drupal\Core\Theme\ThemeInitialization $theme_initialization */
      $theme_initialization = \Drupal::service('theme.initialization');
      $active_theme = \Drupal::theme()->getActiveTheme();
      $config = \Drupal::config('system.theme');
      $defaultTheme =  $config->get('default');
      \Drupal::theme()->setActiveTheme($theme_initialization->getActiveThemeByName($defaultTheme));

      // Rendering node.
      $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
      $build = $view_builder->view($node, 'os2web_newsletter');
      $renderedNode = render($build);

      // Changing theme back.
      \Drupal::theme()->setActiveTheme($active_theme);

      $replacements[$context['tokens']['render_os2web_newsletter']] = $renderedNode;
    }
  }
}

/**
 * Implements template_preprocess_node().
 *
 * Adds relevant info for newsletter template.
 */
function os2web_newsletter_preprocess_node(&$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];
  if ($node->getType() == 'os2web_newsletter') {
    $imageUri = $node->field_os2web_newsltr_picture->entity->field_media_image->entity->getFileUri();
    $altText = $node->field_os2web_newsltr_picture->entity->field_media_image->alt;
    $mainLink = $node->field_os2web_newsltr_prim_link->value;

    $variables['#image_path'] = file_create_url($imageUri);
    $variables['#image_title'] = $altText;
    $variables['#main_link'] = $mainLink;
  }
}

/**
 * Implements template_preprocess_field().
 *
 * Adds relevant info for newsletter template.
 */
function os2web_newsletter_preprocess_field(&$variables) {
  if ($variables['field_name'] == 'field_os2web_newsltr_rel_news') {
    $config = \Drupal::config(SettingsForm::$configName);
    $variables['#all_news_url'] = $config->get('all_news_url');
  }

  if ($variables['field_name'] == 'field_os2web_newsltr_rel_events') {
    $config = \Drupal::config(SettingsForm::$configName);
    $variables['#all_events_url'] = $config->get('all_events_url');
  }
}
